Repository vulkano-rs/vulkano, pull requests merged in 2021-09, with the labels that each got.

#1681 Decreased size of GraphicsPipelineBuilder
  vulkano/src/pipeline/shader.rs
Labels: PR: In review. Comments to address.

#1601 Goodbye vk-sys
  CHANGELOG_VK_SYS.md
  Cargo.toml
  vk-sys/Cargo.toml
  vk-sys/LICENSE-APACHE
  vk-sys/LICENSE-MIT
  vk-sys/src/lib.rs
Labels: PR: Approved. Blocked.

#1700 Exportable memory as dedicated
  vulkano/src/buffer/device_local.rs
  vulkano/src/image/attachment.rs
  vulkano/src/image/storage.rs
  vulkano/src/memory/device_memory.rs
  vulkano/src/memory/pool/host_visible.rs
  vulkano/src/memory/pool/mod.rs
  vulkano/src/memory/pool/non_host_visible.rs
  vulkano/src/memory/pool/pool.rs
Labels: PR: Review next Sunday

#1716 Limit compatibility check for bound descriptor sets to the length of the current layout
  vulkano/src/command_buffer/synced/commands.rs
Labels: PR: Review next Sunday

#1718 Add `AutoCommandBufferBuilder::clear_depth_stencil_image`
  vulkano/src/command_buffer/auto.rs
  vulkano/src/command_buffer/synced/commands.rs
  vulkano/src/command_buffer/sys.rs
  vulkano/src/command_buffer/validity/clear_depth_stencil_image.rs
  vulkano/src/command_buffer/validity/mod.rs
Labels: PR: Review next Sunday
