Repository vulkano-rs/vulkano, pull requests merged in 2021-06, with the labels that each got.

#1599 Auto-generate extensions and features, check requirements
  Cargo.toml
  vulkano/Cargo.toml
  vulkano/autogen/extensions.rs
  vulkano/autogen/features.rs
  vulkano/autogen/fns.rs
  vulkano/autogen/mod.rs
  vulkano/build.rs
  vulkano/src/buffer/sys.rs
  vulkano/src/device/extensions.rs
  vulkano/src/device/features.rs
  vulkano/src/device/mod.rs
  vulkano/src/extensions.rs
  vulkano/src/fns.rs
  vulkano/src/instance/extensions.rs
  vulkano/src/instance/instance.rs
  vulkano/src/instance/mod.rs
  vulkano/src/instance/physical_device.rs
  vulkano/src/lib.rs
  vulkano/src/memory/device_memory.rs
  vulkano/vk.xml
Labels: PR: In review. Comments to address.

#1603 Implement `fmt::Display` for `DisplayMode` and clarify what the return value of `DisplayMode.refresh_rate` means
  vulkano/src/swapchain/display.rs
Labels: PR: Approved. Additional fixes required.

#1614 Better feature and device selection in examples
  examples/src/bin/basic-compute-shader.rs
  examples/src/bin/buffer-pool.rs
  examples/src/bin/debug.rs
  examples/src/bin/deferred/main.rs
  examples/src/bin/dynamic-buffers.rs
  examples/src/bin/dynamic-local-size.rs
  examples/src/bin/image/main.rs
  examples/src/bin/immutable-buffer-initialization.rs
  examples/src/bin/indirect.rs
  examples/src/bin/instancing.rs
  examples/src/bin/msaa-renderpass.rs
  examples/src/bin/multi-window.rs
  examples/src/bin/multiview.rs
  examples/src/bin/occlusion-query.rs
  examples/src/bin/pipeline-caching.rs
  examples/src/bin/push-constants.rs
  examples/src/bin/runtime-shader/main.rs
  examples/src/bin/shader-include/main.rs
  examples/src/bin/specialization-constants.rs
  examples/src/bin/teapot/main.rs
  examples/src/bin/tessellation.rs
  examples/src/bin/triangle.rs
Labels: PR: Review next Sunday

#1622 Rearrange descriptor set modules and types
  examples/src/bin/basic-compute-shader.rs
  examples/src/bin/deferred/frame/ambient_lighting_system.rs
  examples/src/bin/deferred/frame/directional_lighting_system.rs
  examples/src/bin/deferred/frame/point_lighting_system.rs
  examples/src/bin/dynamic-buffers.rs
  examples/src/bin/dynamic-local-size.rs
  examples/src/bin/image/main.rs
  examples/src/bin/immutable-buffer-initialization.rs
  examples/src/bin/indirect.rs
  examples/src/bin/push-constants.rs
  examples/src/bin/shader-include/main.rs
  examples/src/bin/specialization-constants.rs
  examples/src/bin/teapot/main.rs
  vulkano-shaders/src/codegen.rs
  vulkano/autogen/properties.rs
  vulkano/src/command_buffer/auto.rs
  vulkano/src/command_buffer/state_cacher.rs
  vulkano/src/command_buffer/synced/commands.rs
  vulkano/src/command_buffer/sys.rs
  vulkano/src/command_buffer/validity/descriptor_sets.rs
  vulkano/src/descriptor/descriptor_set/sys.rs
  vulkano/src/descriptor/mod.rs
  vulkano/src/descriptor_set/collection.rs
  vulkano/src/descriptor_set/fixed_size_pool.rs
  vulkano/src/descriptor_set/layout/desc.rs
  vulkano/src/descriptor_set/layout/mod.rs
  vulkano/src/descriptor_set/layout/sys.rs
  vulkano/src/descriptor_set/mod.rs
  vulkano/src/descriptor_set/persistent.rs
  vulkano/src/descriptor_set/pool/mod.rs
  vulkano/src/descriptor_set/pool/standard.rs
  vulkano/src/descriptor_set/pool/sys.rs
  vulkano/src/descriptor_set/sys.rs
  vulkano/src/device/mod.rs
  vulkano/src/device/properties.rs
  vulkano/src/lib.rs
  vulkano/src/pipeline/compute_pipeline.rs
  vulkano/src/pipeline/layout/desc.rs
  vulkano/src/pipeline/layout/limits_check.rs
  vulkano/src/pipeline/layout/sys.rs
  vulkano/src/pipeline/shader.rs
  vulkano/src/swapchain/capabilities.rs
Labels: PR: Approved. Additional fixes required.
